spring:
  r2dbc:
    url: r2dbc:h2:mem:///franquicias;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.nequi.franquicias: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
