spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franquicias
    username: root
    password: 
    properties:
      # Configuración de pool de conexiones
      initial-size: 5
      max-size: 10
      validation-query: SELECT 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG
    com.nequi.franquicias: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
