spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/franquicias
    username: root
    password: root
    properties:
      # Configuración de pool de conexiones
      initial-size: 5
      max-size: 10
      validation-query: SELECT 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG
    com.nequi.franquicias: DEBUG

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
